### ISSUE TITLE
while massupdate zhisto records, the archive are updated too

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gigazman/zhisto4sm#20]
```
What steps will reproduce the problem?
1. select record to be massupdate
2. change the version value and click "massupdate"

What is the expected output? What do you see instead?
Expected to change only the version value.
Instead, the archived object is updated too.

Please use labels and text to provide additional information.

bug existing in the version zhisto 3.4.B
```

Original issue reported on code.google.com by `alainzh...@gmail.com` on 23 Jun 2015 at 5:40

**Comment by gigazman** [comment]
issue fixed in version 3.4.D in the formatctrl
if (vars.$zhisto_upd_objet==true)
{
    // à l'ajout le champ record est écrasé
    var objRec
    objRec=lib.alzModif.scGetQryRecord(vars.$file.objet,vars.$file.table)
    if (objRec!=null)
    {
    system.vars.$file.record=objRec.getXML().toXMLString()
    }
vars.$zhisto_upd_objet=null
}
